In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#extra credit: make another kind of regression model


In [ ]:
dataset = pd.read_csv ('/content/CountryData-3.csv')
dataset

Country                               Region  Population  \
0       Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1           Albania   EASTERN EUROPE                          3581655   
2           Algeria   NORTHERN AFRICA                        32930091   
3    American Samoa   OCEANIA                                   57794   
4           Andorra   WESTERN EUROPE                            71201   
..               ...                                  ...         ...   
222       West Bank   NEAR EAST                               2460492   
223  Western Sahara   NORTHERN AFRICA                          273008   
224           Yemen   NEAR EAST                              21456188   
225          Zambia   SUB-SAHARAN AFRICA                     11502010   
226        Zimbabwe   SUB-SAHARAN AFRICA                     12236805   

        Area  Pop. Density  Coastline  Net migration  Infant mortality  \
0     647500          48.0       0.00          23.06            163.07   
1      28748         124.6       1.26          -4.93             21.52   
2    2381740          13.8       0.04          -0.39             31.00   
3        199         290.4      58.29         -20.71              9.27   
4        468         152.1       0.00           6.60              4.05   
..       ...           ...        ...            ...               ...   
222     5860         419.9       0.00           2.98             19.62   
223   266000           1.0       0.42            NaN               NaN   
224   527970          40.6       0.36           0.00             61.50   
225   752614          15.3       0.00           0.00             88.29   
226   390580          31.3       0.00           0.00             67.69   

         GDP  Literacy  Phones  Arable  Crops  Other  Climate  Birthrate  \
0      700.0      36.0     3.2   12.13   0.22  87.65      1.0      46.60   
1     4500.0      86.5    71.2   21.09   4.42  74.49      3.0      15.11   
2     6000.0      70.0    78.1    3.22   0.25  96.53      1.0      17.14   
3     8000.0      97.0   259.5   10.00  15.00  75.00      2.0      22.46   
4    19000.0     100.0   497.2    2.22   0.00  97.78      3.0       8.71   
..       ...       ...     ...     ...    ...    ...      ...        ...   
222    800.0       NaN   145.2   16.90  18.97  64.13      3.0      31.67   
223      NaN       NaN     NaN    0.02   0.00  99.98      1.0        NaN   
224    800.0      50.2    37.2    2.78   0.24  96.98      1.0      42.89   
225    800.0      80.6     8.2    7.08   0.03  92.90      2.0      41.00   
226   1900.0      90.7    26.8    8.32   0.34  91.34      2.0      28.01   

     Deathrate  Agriculture  Industry  Service  
0        20.34        0.380     0.240    0.380  
1         5.22        0.232     0.188    0.579  
2         4.61        0.101     0.600    0.298  
3         3.27          NaN       NaN      NaN  
4         6.25          NaN       NaN      NaN  
..         ...          ...       ...      ...  
222       3.92        0.090     0.280    0.630  
223        NaN          NaN       NaN    0.400  
224       8.30        0.135     0.472    0.393  
225      19.93        0.220     0.290    0.489  
226      21.84        0.179     0.243    0.579  

[227 rows x 20 columns]

In [ ]:
X1 = dataset.iloc[:, 1:8].values
X2 = dataset.iloc[:, 9:].values

X = np.concatenate((X1, X2), axis=1)

y = dataset.iloc[:, 8].values

In [ ]:
print(X)
print()
print(y)

[['ASIA (EX. NEAR EAST)         ' 31056997 647500 ... 0.38 0.24 0.38]
 ['EASTERN EUROPE                     ' 3581655 28748 ... 0.232 0.188
  0.579]
 ['NORTHERN AFRICA                    ' 32930091 2381740 ... 0.101 0.6
  0.298]
 ...
 ['NEAR EAST                          ' 21456188 527970 ... 0.135 0.472
  0.393]
 ['SUB-SAHARAN AFRICA                 ' 11502010 752614 ... 0.22 0.29
  0.489]
 ['SUB-SAHARAN AFRICA                 ' 12236805 390580 ... 0.179 0.243
  0.579]]

[  700.  4500.  6000.  8000. 19000.  1900.  8600. 11000. 11200.  3500.
 28000. 29000. 30000.  3400. 16700. 16900.  1900. 15700.  6100. 29100.
  4900.  1100. 36000.  1300.  2400.  6100.  9000.  7600. 16000. 18600.
  7600.  1100.  1800.   600.  1900.  1800. 29800.  1400. 35000.  1100.
  1200.  9900.  5000.  6300.   700.   700.   700.  5000.  9100.  1400.
 10600.  2900. 19200. 15700. 31100.  1300.  5400.  6000.   500.  3300.
  4000.  4800.  2700.   700. 12300.   700. 22000.  5800. 27400. 27600.
  8300. 17500.  5500.  170

In [ ]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:])
X[:, 2:] = imputer.transform(X[:, 2:])

In [ ]:
print(X[:, 5])

[23.06 -4.93 -0.39 -20.71 6.6 0.0 10.76 -6.15 0.61 -6.47 0.0 3.98 2.0 -4.9
 -2.2 1.05 -0.71 -0.31 2.54 1.23 0.0 0.0 2.49 0.0 -1.32 0.31 0.0 -0.03
 10.01 3.59 -4.58 0.0 -1.8 -0.06 0.0 0.0 5.96 -12.07 18.75 0.0 -0.11 0.0
 -0.4 -0.31 0.0 0.0 -0.17 0.038124999999999985 0.51 -0.07 1.58 -1.58 0.43
 0.97 2.48 0.0 -13.87 -3.22 0.0 -8.58 -0.22 -3.74 0.0 0.0 -3.16 0.0 1.41
 -3.14 0.95 0.66 6.27 2.94 0.0 1.57 1.6 -4.7 2.18 -0.64 0.0 2.35 -8.37
 -13.92 -0.15 0.0 -1.67 3.84 -3.06 -1.57 -2.07 -3.4 -1.99 5.24 0.86 2.38
 -0.07 0.0 -0.84 0.0 4.99 5.36 0.68 2.07 -4.92 0.0 2.76 6.59 -3.35 -0.1
 0.0 0.0 0.0 14.18 -2.45 0.0 -2.23 0.0 -0.74 0.0 0.0 4.85 -0.71 8.97 4.86
 -1.45 0.0 0.0 0.0 0.0 -0.33 2.07 -6.04 -0.05 0.0 -0.9 6.78 -4.87 -20.99
 -0.26 7.75 0.0 0.0 -0.98 0.0 0.0 0.0 0.0 2.91 -0.41 0.0 4.05 -1.22 -0.67
 0.26 9.61 1.74 0.28 -2.77 2.85 -0.91 0.0 -0.08 -1.05 -1.5 -0.49 3.57
 -1.46 16.29 0.0 -0.13 1.02 0.0 0.0 -7.11 -2.67 -4.86 -7.64 -11.7 10.98
 -2.72 -2.71 0.2 -1.33 -5.69 0.0 11.53 0.3 1.12 0.0 5.3

In [ ]:
pd.DataFrame(y).isnull().sum()

0    1
dtype: int64

In [ ]:
y = np.nan_to_num(y,nan=50000)

In [ ]:
y.mean()

9867.400881057269

In [ ]:
print(y)

[  700.  4500.  6000.  8000. 19000.  1900.  8600. 11000. 11200.  3500.
 28000. 29000. 30000.  3400. 16700. 16900.  1900. 15700.  6100. 29100.
  4900.  1100. 36000.  1300.  2400.  6100.  9000.  7600. 16000. 18600.
  7600.  1100.  1800.   600.  1900.  1800. 29800.  1400. 35000.  1100.
  1200.  9900.  5000.  6300.   700.   700.   700.  5000.  9100.  1400.
 10600.  2900. 19200. 15700. 31100.  1300.  5400.  6000.   500.  3300.
  4000.  4800.  2700.   700. 12300.   700. 22000.  5800. 27400. 27600.
  8300. 17500.  5500.  1700.   600.  2500. 27600.  2200. 17500. 20000.
 20000.  5000.  8000. 21000.  4100. 20000.  2100.   800.  4000.  1600.
  2600. 28800. 13900. 30900.  2900.  3200.  7000.  1500. 29600. 21000.
 19800. 26700.  3900. 28200. 24800.  4300.  6300.  1000.   800.  1300.
 17800. 19000.  1600.  1700. 10200.  4800.  3000.  1000.  6400. 25000.
 11400. 55100. 19400.  6700.   800.   600.  9000.  3900.   900. 17700.
  1600. 14400.  1800. 11400.  2600.  9000.  2000.  1800. 27000.  1800.
  3400

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 0.38 0.24 0.38]
 [0.0 0.0 0.0 ... 0.232 0.188 0.579]
 [0.0 0.0 0.0 ... 0.101 0.6 0.298]
 ...
 [0.0 0.0 0.0 ... 0.135 0.472 0.393]
 [0.0 0.0 0.0 ... 0.22 0.29 0.489]
 [0.0 0.0 0.0 ... 0.179 0.243 0.579]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train)

[[0.0 0.0 0.0 ... 0.463 0.203 0.334]
 [0.0 0.0 0.0 ... 0.01 0.204 0.787]
 [0.0 0.0 1.0 ... 0.213 0.233 0.555]
 ...
 [0.0 0.0 0.0 ... 0.769 0.054 0.177]
 [0.0 0.0 0.0 ... 0.151 0.096 0.753]
 [0.0 0.0 0.0 ... 0.035 0.258 0.707]]


In [ ]:
print(y_train)

[  600. 37800.  1800.  2200. 26700. 11800. 22000.  2500.  1900. 28600.
  1300.  4700.  7400. 36000. 21600.  2600.   700.  9000. 19000. 17800.
  4800. 19200. 22000.  9000. 21500.  1200.  3400.  9000.  1600.  2400.
  7600.  6700.  4000.  5400.   800. 24800. 29100.  1300.  6400. 31100.
  7800. 20000.  2900. 19000.  2100. 23400.  2100. 27000. 17700.  5100.
  3000.  9900. 16700.  7600. 10600.  6900.  4900.  1600.   700. 13100.
   800. 19000.  2200.  2700.   600.  6000.  3300.  1800.  4800.  6300.
  1200. 28000.   900.  1700.  2900. 17200.  1600.  1500.  9500. 29600.
  8000. 30900.  2000.  1700.  1700.   700.  2900.  3200. 27600.  1400.
  9100. 20000.   800.  1300. 17500. 19800. 14400.   500.   800.  8600.
 27400.  4100. 55100. 23200.  1900.  4900.  1700.  5800. 28800.  1400.
 29000. 25000.  3900.  1800.  6000.   700.  4500. 11400.  2200.  5000.
  4300.  1800. 32700. 15700. 35000. 11400. 15700. 18000.  3700.   900.
  1900. 16000. 10200. 11100.   800.  1100. 13300.  3900.   600.  1800.
  5800

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 13:] = sc.fit_transform(X_train [:, 13:])
X_test[:, 13:] = sc.transform(X_test [:, 13:])

In [ ]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
print(y_pred)

[  629.93356383 16257.12815046  5445.03250253 17785.66760623
 28950.86728823 13727.17239439  5761.23808539  6791.90931964
  6150.11032438 19524.97743392  7966.77750337  4454.44627798
 11084.25682139  9552.16163135 14227.85153043  -765.72824371
  4046.53259337  2352.18075085  -399.96658695 11765.2565161
  5697.91649067  8284.57840133  8521.21488345  3683.60615814
  2340.59376276  3820.8791604  -1613.92595506  4433.59114277
 23932.71469796 11233.6458776   3684.01273632  6534.68418682
  5792.3654443   3511.33635151 23776.62564349 10664.85005915
 13184.1879288   1239.93502057 13556.93316209 12212.72828662
  6502.71636653 11778.55393386   663.956563    3353.12975323
 12991.21131492 13941.78469741]


In [ ]:
residuals = y_test - y_pred
print(residuals)

[   970.06643617   4742.87184954    854.96749747   5914.33239377
  -1350.86728823 -11227.17239439  -3161.23808539  -6191.90931964
  -5050.11032438 -10624.97743392  -2966.77750337  -2954.44627798
   1215.74317861   1647.83836865  -1727.85153043   1265.72824371
    -46.53259337   -452.18075085   1099.96658695  -2165.2565161
  -1997.91649067  -1084.57840133  -1521.21488345   1916.39384186
  -1540.59376276  -3120.8791604    2613.92595506  -3033.59114277
   6067.28530204   8166.3541224     915.98726368   2465.31581318
    507.6345557   -2211.33635151  14023.37435651  -4564.85005915
   3715.8120712    1060.06497943  -2556.93316209  -5212.72828662
  -1102.71636653  -5078.55393386    736.043437    -2353.12975323
    908.78868508   3558.21530259]


In [ ]:
regressor.score(X_test, y_test)

0.7434511487168624